# Generated by Django 5.0.7 on 2024-07-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_category_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='rate_to_usd',
            new_name='amount_equal_usd',
        ),
    ]
