# Generated by Django 5.0.7 on 2024-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_rename_rate_to_usd_currency_amount_equal_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='amount_equal_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
