# Generated by Django 5.0.7 on 2024-07-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_currency_amount_equal_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
